### ISSUE TITLE
Manage instantly counter plural

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#117]
See https://forum.cozy.io/t/cozy-photos-does-not-manage-items-singular-plural-instantly/425
When uploading photos to an album, we should update the counter singular / plural.
Thanks @goofy-bz for noticing.

**Comment by 0gust1** [comment]
Pluralization does not work at the moment.

Polyglot wants a `smart_count` parameter with a length attribute to manage pluralization, and actually it's an number which is passed. This behavior is fixed in the current version of polyglot (https://github.com/airbnb/polyglot.js/blob/master/lib/polyglot.js#L200)

I don't know what to do here. The proper way would be to use the last version of polyglot, but actually the dependency is not managed with npm :-/

**Comment by clochix** [comment]
Thanks for your fix @0gust1, it works fine now, @goofy-bz will be happy ☺

**Comment by ghost** [comment]
Confirmed. 
![clipgoofyhat](https://cloud.githubusercontent.com/assets/858630/12297759/e70725dc-ba0e-11e5-861a-0f7cd4ab25ca.png)
/me hats off for 0gust1

**Comment by 0gust1** [comment]
Thanks, it was not a tremendous contribution, but I was glad to help a little :)
