### ISSUE TITLE
photo max size 

### ISSUE THREAD

**Issue by ldgeo** [cozy/cozy-photos-v2#29]
Hello, 
i tried cozy on my own server.
I didn't manage to upload an image >= 1MB ?

I got this error :
"IMG_456.JPG  : upload failled"

Is there a way to increase the max size for uploading photos?

**Comment by aenario** [comment]
Hi Idgeo, 

Max upload size is 10MB at the cozy-photos level : https://github.com/mycozycloud/cozy-photos/blob/master/server/config.coffee#L23

So the problem is probably upstream. How did you install cozy ? Of the top of my head, it can come from any of the followings : 
- nginx configuration (did you change the default that come with cozy)
- some limit / timeout at your server or router
- RAM limit and no swap file at the OS level

**Comment by ldgeo** [comment]
I installed cozy with the fabfile provided in the cozy-setup on a debian wheezy.
I thought that the nginx config was in consistency with the cozy-photos rules.

I added the client_max_body_size parameter to my nginx conf and all is fine now.

Thanks !!

**Comment by frankrousseau** [comment]
Great! I will add it to the troubleshootings section.

**Comment by dolanor** [comment]
Just as a remark, I did install cozycloud on an LXC container.

By default, I could upload images bigger than 1MB, but smaller than 10MB.
(Since I'm trying to upload videos, I tried to increase that limit, but it seems my app.js stays the same even if I change the https://github.com/mycozycloud/cozy-photos/blob/master/server/config.coffee#L23 line)
